import { defineConfig } from "vitest/config";
import mdx from "fumadocs-mdx/vite";
import { docs, default as sourceConfig } from "./source.config";
import path from "node:path";

export default defineConfig(async () => ({
  plugins: [
    await mdx({ docs, default: sourceConfig } as Record<string, unknown>, {
      index: false,
    }),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./"),
      // .source/ is generated by fumadocs-mdx (run via the pretest script or postinstall).
      // The vite plugin above also writes .source/ during transform, but the alias resolver
      // runs before transform, so the directory must already exist when vitest starts.
      "collections/server": path.resolve(__dirname, ".source/server.ts"),
    },
  },
  test: {
    environment: "happy-dom",
    include: ["__tests__/**/*.test.ts", "__tests__/**/*.test.tsx"],
    globals: false,
  },
}));
